export const VOICE_STYLE = [
  { label: '兴奋而高能量', value: 'advertisement_upbeat' },
  { label: '温暖而深情', value: 'affectionate' },
  { label: '愤怒和恼怒', value: 'angry' },
  { label: '温暖而轻松', value: 'assistant' },
  { label: '冷静而镇定', value: 'calm' },
  { label: '随意', value: 'chat' },
  { label: '快乐积极', value: 'cheerful' },
  { label: '客户友好', value: 'customerservice' },
  { label: '忧郁和沮丧', value: 'depressed' },
  { label: '不屑和抱怨', value: 'disgruntled' },
  { label: '轻松、有趣和信息丰富', value: 'documentary-narration' },
  { label: '感到不舒服时表达不确定和犹豫', value: 'embarrassed' },
  { label: '表达关怀和理解', value: 'empathetic' },
  { label: '表达一种钦佩的语气', value: 'envious' },
  { label: '表达乐观和充满希望', value: 'excited' },
  { label: '表达害怕和紧张的音调', value: 'fearful' },
  { label: '愉快、诱人和温暖', value: 'friendly' },
  { label: '温和、礼貌', value: 'gentle' },
  { label: '表达愉快、诱人和温暖的语气', value: 'hopeful' },
  { label: '旋律和感伤', value: 'lyrical' },
  { label: '表达专业、客观的内容阅读语气', value: 'narration-professional' },
  { label: '正式和专业的', value: 'newscast' },
  { label: '表达一般新闻传递的多功能和随意的语气', value: 'newscast-casual' },
  { label: '表达正式、自信和权威的新闻传递语气', value: 'newscast-formal' },
  { label: '诗朗诵', value: 'poetry-reading' },
  { label: '悲伤', value: 'sad' },
  { label: '严厉而命令的语气', value: 'serious' },
  { label: '听起来好像声音的音调', value: 'shouting' },
  { label: '广播体育', value: 'sports_commentary' },
  { label: '广播体育中的激动人心的时刻', value: 'sports_commentary_excited' },
  { label: '表达一种柔和的音调', value: 'whispering' },
  { label: '害怕的语气，节奏更快，声音更颤抖', value: 'terrified' },
  { label: '表达一种冷漠的语气', value: 'unfriendly' },
]

export const VOICE_STYLE_MAP = Object.fromEntries(VOICE_STYLE.map((item) => [item.value, item.label]))
