export const VOICE_STYLE = [
  // { label: '-', value: 'advertisement_upbeat' },
  // { label: '-', value: 'affectionate' },
  { label: '愤怒', value: 'angry' },
  // { label: '-', value: 'assistant' },
  { label: '冷静', value: 'calm' },
  { label: '轻松', value: 'chat' },
  { label: '愉快', value: 'cheerful' },
  { label: '热情', value: 'customerservice' },
  { label: '忧郁', value: 'depressed' },
  { label: '轻蔑', value: 'disgruntled' },
  { label: '专业', value: 'documentary-narration' },
  { label: '尴尬', value: 'embarrassed' },
  { label: '关心', value: 'empathetic' },
  { label: '佩服', value: 'envious' },
  { label: '幽默', value: 'excited' },
  { label: '不安', value: 'fearful' },
  { label: '友好', value: 'friendly' },
  { label: '绅士', value: 'gentle' },
  { label: '期望', value: 'hopeful' },
  { label: '高雅', value: 'lyrical' },
  { label: '客观', value: 'narration-professional' },
  { label: '舒缓', value: 'narration-relaxed' },
  { label: '新闻', value: 'newscast' },
  { label: '随意', value: 'newscast-casual' },
  { label: '自信', value: 'newscast-formal' },
  { label: '朗诵', value: 'poetry-reading' },
  { label: '悲伤', value: 'sad' },
  { label: '严肃', value: 'serious' },
  { label: '喊叫', value: 'shouting' },
  // { label: '-', value: 'sports_commentary' },
  // { label: '-', value: 'sports_commentary_excited' },
  // { label: '-', value: 'whispering' },
  // { label: '-', value: 'terrified' },
  // { label: '-', value: 'unfriendly' },
]

export const VOICE_STYLE_MAP = Object.fromEntries(
  VOICE_STYLE.map((item) => [item.value, item.label]).filter((item) => item[0] !== '-')
)
